### ISSUE TITLE
keep empty lines

### ISSUE THREAD

**Issue by lekoala** [silverleague/silverstripe-ideannotator#108]
When running the tool, it removes all empty lines in the code which reduce readability (on top off adding unnecessary file changes).

Whould it be possible to set the code formatter so that it preserves empty lines?

(tested on win10)

**Comment by lekoala** [comment]
as far as I can tell, it's quite simple to fix

https://github.com/silverleague/silverstripe-ideannotator/pull/109

**Comment by Firesphere** [comment]
Closing this issue as the PR in #107 solves this.
