### ISSUE TITLE
Suggestion: Import instead of inline FQN

### ISSUE THREAD

**Issue by tractorcow** [silverleague/silverstripe-ideannotator#114]
In most cases many of the method return types are imported, and if not the module could add them.

`* @method ManyManyList|Tag[] Tags()` is a lot more readable than `* @method \SilverStripe\ORM\ManyManyList|Tag[] Tags()`

**Comment by Firesphere** [comment]
Current implementation is you can set it to use short names, but it doesn't check if the class is actually in the `use` statements. 

See bottom of Installation doc: https://github.com/silverleague/silverstripe-ideannotator/blob/master/docs/en/Installation.md

**Comment by robbieaverill** [comment]
I'm not that familiar with this module, but I assume we'd need a PHP parser to be able to do this. I like the idea though!

**Comment by robbieaverill** [comment]
`use_short_name: true` does this, but it doesn't import the namespace (as @Firesphere noted)

**Comment by Firesphere** [comment]
Closing as per the same logic I applied here:
https://github.com/silverleague/silverstripe-ideannotator/issues/120#issuecomment-1471586190
