### ISSUE TITLE
has_many, many_many etc should import the namespace for HasManyList etc

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverstripe-ideannotator#120]
Example model:

```php
namespace Foo;
class Foo extends \SilverStripe\ORM\DataObject
{
    private static $has_many = [
        'Bars' => Bar::class,
    ];
}

namespace Bar;
class Bar extends \SilverStripe\ORM\DataObject {}
```

When running dev/build you'll get this in the Foo docblock:

```php
* @method DataList|Bar[] Bars()
```

It's missing `use SilverStripe\ORM\DataList;` imported - this is a bug

**Comment by Firesphere** [comment]
Isn't this pretty much what is covered in #114 ?

I like the use statement addition though, but I'm not sure how to parse that, would probably end up using regex to check if it's already there...

**Comment by Firesphere** [comment]
This is only a valid issue if the shortname feature is enabled.

I agree though, it's pretty annoying

**Comment by Firesphere** [comment]
Closing this for now, changing `use` statements feels like touching active code, which I'd rather avoid.

Feel free to open again if you disagree.
