### ISSUE TITLE
how do you use this module?

### ISSUE THREAD

**Issue by sunnysideup** [silverleague/silverstripe-ideannotator#131]
I am keen to run this from the command line on a vendor module, rather than app/mysite. 

Would it be OK to have something like this:

```
if(Director::isCli()) {
    Config::inst()->update(DataObjectAnnotator::class, 'enabled_modules', [$this->request->getVar('module')]);
}
```

**Comment by robbieaverill** [comment]
The readme says that you can define these in YAML configuration. We should ensure that vendor modules work with that syntax. Even though it's normally not something you'd do, SilverStripe developers often develop in the vendor folder.

I assume your `Director::isCli()` statement is to avoid mutating the config manifest for regular site requests, since this is in a `_config.php` file? Does the documented YAML config convention not work for vendor modules?

**Comment by sunnysideup** [comment]
I am trying to use this module with some automation, so ideally, I would just run:

composer install module ...
run task
composer uninstall

rinse and repeat over a large number of modules. 

It is not such a biggie, but I guess what I sensing is that once you install the module you still have to enable it and allow modules, whereas, installed in dev only environment that seems a bit OTT / double-up.

**Comment by robbieaverill** [comment]
I'm not sure what you're suggesting as an alternative - we can't annotate every module you have installed automatically.

Perhaps your automation could create and delete `app/_config/annotator.yml` with the necessary config for each temporary module in it?

**Comment by sunnysideup** [comment]
Hi Robbie,

Thank you for all your responses.  This is how I will approach it.

**Comment by Firesphere** [comment]
Question: Why would you want to install and then uninstall the module again each time?

**Comment by sunnysideup** [comment]
Basically, I want to run it through all my modules BUT having it hanging on every module may cause conflicts (e.g. PHP UNIT) and so I only want to run it from time to time and then remove again.

I guess I could probably leave it though because dev requirements are not added to third-party projects.

**Comment by Firesphere** [comment]
You could use the `enabled` flag:
```
SilverLeague\IDEAnnotator\DataObjectAnnotator:
    enabled: true
```

As per the docs https://github.com/silverleague/silverstripe-ideannotator/blob/master/docs/en/Installation.md

**Comment by robbieaverill** [comment]
What do you suggest we do to close this issue @Firesphere?
