### ISSUE TITLE
modules are not identified correctly in the Silverstripe core - which means this module is broken

### ISSUE THREAD

**Issue by sunnysideup** [silverleague/silverstripe-ideannotator#132]
see: https://github.com/silverstripe/silverstripe-framework/issues/9561

modules are not identified correctly, which means that some modules can not be annotated.

**Comment by robbieaverill** [comment]
Thanks for the bug report. Do you have an idea of what could be changed in this module to fix the bug, if anything? If it's something that needs to be fixed entirely in framework then I suggest we close this one.

**Comment by robbieaverill** [comment]
Let's track this issue in https://github.com/silverstripe/silverstripe-framework/issues/9561
