### ISSUE TITLE
Lack of stable 3.x release.

### ISSUE THREAD

**Issue by tractorcow** [silverleague/silverstripe-ideannotator#135]
I noticed there have been quite a few changes, but no stable tag for 3.0 in a while. Could I please request one?

**Comment by Firesphere** [comment]
Sure thing, got any specific comit in mind?

**Comment by Firesphere** [comment]
Is 2.x maybe what you're looking for?

Version 3 has been skipped on purpose, to closer match the SS4 releases, afaik. That may throw you off, and that could be documented better indeed.

**Comment by robbieaverill** [comment]
We have a stable 3.0.x release line for Silverstripe 4. I've just tagged 3.0.1 from the 3.0 branch.

**Comment by tractorcow** [comment]
Thanks @robbieaverill :D

**Comment by tractorcow** [comment]
A 3.0 tag was helpful, but there is still the matter of this.

![image](https://user-images.githubusercontent.com/936064/96386794-ffbc6e00-11f9-11eb-9dbe-d8648ffd298b.png)

Perhaps we need a 3.1 tag as well?

**Comment by robbieaverill** [comment]
Sure!

**Comment by tractorcow** [comment]
You are a breath of fresh air @robbieaverill :)
