### ISSUE TITLE
Crash when using Versioned.versioned

### ISSUE THREAD

**Issue by oddnoc** [silverleague/silverstripe-ideannotator#143]
In projects using the `Versioned::class . '.versioned'` variant (versions without staging, see [docs](https://docs.silverstripe.org/en/4/developer_guides/model/versioning/#implementing-a-versioned-dataobject)), the annotator throws:

`ERROR [UNKNOWN TYPE, ERRNO -1]: Uncaught ReflectionException: Class "SilverStripe\Versioned\Versioned.versioned" does not exist`

**Comment by Firesphere** [comment]
I noticed this as well in other places. It's the dot notation that breaks things specifically

**Comment by Firesphere** [comment]
This should be resolved in 3.2.3.
