### ISSUE TITLE
property has invalid value (\Page dataRecord)

### ISSUE THREAD

**Issue by andersbjorkland** [silverleague/silverstripe-ideannotator#144]
## Setup
PHP 8.0
Silverstripe CMS v4.11.0
SilverLeague IDEAnnotator v3.2
PHPStan v1.8

## Bug
When running dev/build the IDEAnnotator will add the following PHPDoc to the default PageController in SilverStripe:

```php
<?php

namespace {

/**
 * Class \PageController
 *
 * @property \Page dataRecord
 * @method \Page data()
 * @mixin \Page
 */
class PageController extends \SilverStripe\CMS\Controllers\ContentController
// ...
```

Running PHPStan to analyze, it will react to the annotations with the following message:
```bash
  Line   PageController.php                                                                                                        
 ------ -------------------------------------------------------------------------------------------------------------------------- 
  12     PHPDoc tag @property has invalid value (\Page dataRecord): Unexpected token "dataRecord", expected variable at offset 51  
 ------ -------------------------------------------------------------------------------------------------------------------------- 
```

The property `dataRecord` is not correctly defined as a variable as it is missing the `$`-sign.

## Solution
Fix generation for this property in `ControllerTagGenerator`

**Comment by Firesphere** [comment]
Interesting. This is specific to `dataRecord` that it's not getting the prefixed `$`, that's an oversight somewhere a few weeks/months back!

Thanks!

Did you check if any tests needed updating too?

**Comment by andersbjorkland** [comment]
Sorry, no. Did a quick fix straight on github.dev.

**Comment by wernerkrauss** [comment]
Hi @Firesphere, would you mind releasing a tag release with this fix? PHPStan is complaining about that property thingie...

**Comment by Firesphere** [comment]
Tagged
