### ISSUE TITLE
test suite return types

### ISSUE THREAD

**Issue by lekoala** [silverleague/silverstripe-ideannotator#152]
not sure why, but i my project i got notices due to the setUp and tearDown methods not having the right signature
they should have :void return type

**Comment by Firesphere** [comment]
That is probably a strict type check issue in the PHP settings.
Given I'd like to dump 7.4 support anyway, I can probably just make it all strictly typed.

I can't promise I'll get it done soon though.
Module should still work none the less :)

As usual, PRs are welcome, but I totally understand it if you are about as short on time as I am!
