### ISSUE TITLE
Namespaced classes not always annotated

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-ideannotator#71]
I get this error:
`Could not find string 'class Firesphere\YubiAuth\SiteConfigExtension'. Please check casing and whitespace.`

This is wrong, as it should look for `class SiteConfigExtension`, since the NameSpacing is not in the Class declaration but in the Namespace declaration.

**Comment by Zauberfisch** [comment]
Is this issue still present?

In my work on the new release for SilverStripe 4 I did not notice any issues dealing with namespaces.

**Comment by Firesphere** [comment]
I still seem to get it on SS3.5

**Comment by jelicanin** [comment]
Hi @Firesphere @Zauberfisch ,
I've just hit same issue and you are right.
If you install this module with composer in ss3 project composer will get "^2.0" and latest tag is 2.0.7 which is behind my fix. 

Simple solution would be to make 2.0.7 tag with same [fix](https://github.com/silverleague/silverstripe-ideannotator/pull/72)?

**Comment by Firesphere** [comment]
As far as I know, this has been resolved for SS4 on `master`. Does it need to be fixed for SS3?

**Comment by Firesphere** [comment]
I can't seem to reproduce this anymore?

**Comment by Firesphere** [comment]
Nope, still occasionally happening it seems... Send in the cavalry

**Comment by Firesphere** [comment]
Fixed it seems. Closing. If anyone runs in to the same issue, we'll get an issue.

**Comment by andrewandante** [comment]
Ping 😄 

Having this issue on 3.6 - would sure be grand if the fix was backported!
