### ISSUE TITLE
DataObjectTest_Player vs DataObjectAnnotatorTest_Player

### ISSUE THREAD

**Issue by Zauberfisch** [silverleague/silverstripe-ideannotator#75]
The unit tests reference a class `DataObjectTest_Player` which does not exist. But `DataObjectAnnotatorTest_Player` exists.

[DataObjectAnnotatorTest_TeamChanged.php#L16](https://github.com/axyr/silverstripe-ideannotator/blob/b7b2c08daf3f1121846e69a4b487ed8198db77ef/tests/mock/DataObjectAnnotatorTest_TeamChanged.php#L16)
[DataObjectAnnotatorTest_Team_Extension.php#L12](https://github.com/axyr/silverstripe-ideannotator/blob/b7b2c08daf3f1121846e69a4b487ed8198db77ef/tests/mock/DataObjectAnnotatorTest_Team_Extension.php#L12)
[DataObjectAnnotatorTest_Player.php](https://github.com/axyr/silverstripe-ideannotator/blob/b7b2c08daf3f1121846e69a4b487ed8198db77ef/tests/mock/DataObjectAnnotatorTest_Player.php)

Is this on purpose to test a case where a class would not exist or can I fix this class name?

**Comment by Firesphere** [comment]
It doesn't really matter, as the test is about updating the docblocks. So being totally false sounds like the sane thing to do actually

**Comment by Zauberfisch** [comment]
Alright, thanks for the response, I've decided to fix this by renaming it to the valid class name in my work on the new release for SilverStripe 4 (#79).
We should back-port this fix after we have tagged the new major release.
