### ISSUE TITLE
Should pushMethodTag() check for existing methods on the current class only?

### ISSUE THREAD

**Issue by Zauberfisch** [silverleague/silverstripe-ideannotator#78]
Should we perform the [hasMethod](https://github.com/axyr/silverstripe-ideannotator/blob/7b2b47f8b6f8c14a8ad3e9ca24e630cc44ad1111/code/Generators/AbstractTagGenerator.php#L158) check differently to identify if a method exists on the current class instead of it's parent?

Please see the related issue #77 for details.

**Comment by Firesphere** [comment]
Technically speaking, the test should cover it. So yes? :)

**Comment by Zauberfisch** [comment]
I believe the solution would be quiet straight forward using getMethod().


    /**
     * @param string $methodName
     * @param string $tagString
     */
    protected function pushMethodTag($methodName, $tagString)
    {
        if (!$this->reflector->hasMethod($methodName) || $this->reflector->getMethod($methodName)->getDeclaringClass()->getName() != $this->reflector->getName()) {
            $this->tags['methods'][$tagString] = $this->pushTagWithExistingComment('method', $tagString);
        }
    }

I agree that we should change it, but why I am raising this question is: I am not sure if there are side effects that I didn't think of.

**Comment by Firesphere** [comment]
Yes, in the pipeline for RC2 if you ask me. Sticky note is on the to-do board here!

**Comment by Firesphere** [comment]
I had a thought about this and I'm thinking no. a method should be unique, thus if you have a duplicate, the problem is in your own code. and a getter/setter method does not interfere with the actual annotations as such.
