### ISSUE TITLE
Version 3 / SilverStripe 4 support

### ISSUE THREAD

**Issue by Zauberfisch** [silverleague/silverstripe-ideannotator#79]
I have spent the better part of the night porting this module to SilverStripe 4 and would like to tag a new release now. 
According to the mailing list both the SilverStripe community and the composer guys suggest solving multiple framework versions with multiple major releases. 
Therefore I would like to propose to make this release "3.0", so we would maintain "2.x" for SilverStripe 3  and "4.x" for SilverStripe 4.

Is that alright with you guys @axyr @Firesphere?

And, how to we manage branches. Following the example of SilverStripe we should make master the branch for version 3 (SilverStripe 4) and create a new branch for version 2.
Can I go ahead and re-arrange the branches?

**Comment by Zauberfisch** [comment]
PS: I've pushed my update to a new branch "3" already if you care to take a look.

**Comment by Firesphere** [comment]
I would like to have a 4.x branch/release cycle for SS4, and stick to 2.x for SS3

**Comment by Zauberfisch** [comment]
That doesn't necessarily contradict my suggestion of having master as 4 and a 2.x branch nor does it confirm you agree with me, please clarify your statement.

**Comment by Firesphere** [comment]
The branch name is `3`, which confused me. What are you aiming for exactly?

**Comment by Zauberfisch** [comment]
The current release is version 2. the next release, supporting ss4 would then be 3. Therefore I have named the branch 3 (following the example of SilverStripe).

**Comment by Firesphere** [comment]
Although that makes sense... I think naming it `4` would clarify a bit more, the `4` releases are for 4, anything below that works for 3?

I'm actually not entirely sure about it myself, but my thought is to avoid the same confusion I initially had.

**Comment by Zauberfisch** [comment]
I've asked this very question on the dev mailing list a while back and had several conversations about it on irc.
And what I have taken away from that is that it's better not to tie module versions to SilverStripe versions but instead follow semver.
(To tie it to SilverStripe Versions would necacerily mean that we can not follow semver or we would need to hold back features for unreasonable times to be able to release them together with SilverStripe).

With that in mind, we now have 3 different options:

1. 2 different repos `axyr/silverstripe3-ideannotator` and `axyr/silverstripe4-ideannotator` or something - this would allow us to follow semver in each repo
2. Extend the version numbers for an extra diggit, so we have ss3.2.x.x and ss4.2.x.x - this kind of makes sense, but not sure how well it integrates with existing tools and workflows
3. follow semver to the letter and make the releases names unrelated the it's dependencies. I've been told it's perfectly fine to have version 2 be ss3, version 3 be ss4 and then for the next major release have version 4 be the next ss3 and version 5 the next ss4 release.

To me, option 3 makes the most sense, and while it seems counter intitive at first, it is actually perfectly valid and in the end it will not matter much anyway, because we have tools like composer that will handle that anyway.

**Comment by Firesphere** [comment]
Valid point. I think starting 2 branches, separately from master, something alike master-ss3 and master-ss4, to start the releases of?

**Comment by Firesphere** [comment]
Besides the current skipped test (which only happens in Travis and nowhere else for me), I think it's okay to make it a SS4-Alpha pre-release version?

My suggestion would be to make it `3.0-alpha1 pre-release`

**Comment by robbieaverill** [comment]
My thoughts on this are that the master branch should be SS4 compat until SS4 is in beta, at which point we (as the framework will) should branch it off to the next major version at the time - likely to be `3`. The `2` branch will maintain support for SS3, and the `3` branch for SS4. It's semver, so we'll just need to ensure we don't break any public APIs for SS3 compatible code.
