### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-ideannotator#80]
I think it would be a good idea to start using a pre-commit hook to format the code to PSR-2 standards.

You'll need to require `    "friendsofphp/php-cs-fixer": "~2.0"` as dev-dependency for the one I usually use:
https://gist.github.com/Firesphere/d2df6d902870620209e493b5a9fbb28f

**Comment by robbieaverill** [comment]
Personally I'm not a fan of doing this. Perhaps better to provide a PHPCS template like [this one](https://github.com/silverstripe/silverstripe-installer/blob/3.4/phpcs.xml.dist)?

**Comment by robbieaverill** [comment]
I think this is covered in #82 now

**Comment by Firesphere** [comment]
Close then, I guess?
