### ISSUE TITLE
Reconfigure CI builds, add Codecov.io and PHPCS config

### ISSUE THREAD

**Issue by robbieaverill** [silverleague/silverstripe-ideannotator#82]
Since the repository has been transferred we will need to reconfigure Travis and Scrutinizer, and would be good to set up Codecov.io

[Repository templates here.](https://github.com/silverleague/silverleague.github.io/wiki/Repository-templates)

**Comment by robbieaverill** [comment]
PHPCS configuration should ideally pass on the [SilverStripe 3.x standards](https://github.com/silverstripe/silverstripe-installer/blob/3.4/phpcs.xml.dist) which are PSR-2 based for 3.x, and straight PSR-2 for SS4 compatible branches

**Comment by Firesphere** [comment]
Is this still an issue?

**Comment by robbieaverill** [comment]
It looks like they're both configured, we just need to fix the readme badges

**Comment by Firesphere** [comment]
Resolved with #94, closing this issue. Further discussion should happen on the PR.
