### ISSUE TITLE
SS4 support for extensions fails

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-ideannotator#88]
Currently, with the removal of Object, extensions are not detected anymore.

**Comment by wernerkrauss** [comment]
Still broken in Silverstripe 4-beta-2: 

`Fatal error: Class 'SilverStripe\Core\Object' not found in /vagrant/www/ideannotator/code/DataObjectAnnotator.php on line 24`

**Comment by Firesphere** [comment]
Fixed on last #3 branch. Waiting for some PR's before finishing.

Tests failing are not related to actual issues but to setup problems
