### ISSUE TITLE
Update to DocBlockGenerator 4

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-ideannotator#91]
Current version 2.0 is not the latest anymore

**Comment by ivoba** [comment]
Actually it should update to v4 of phpdocumentor/reflection-docblock.
Currently i cant install this module because of conflicts with phpunit.

> Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
>     - Installation request for silverleague/ideannotator ^3.0 -> satisfiable by silverleague/ideannotator[3.0, 3.0-beta1, 3.0.0-alpha1, 3.x-dev, 3.0.x-dev].
>     - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
>     - silverleague/ideannotator 3.0.0-alpha1 requires phpdocumentor/reflection-docblock ^2.0.4 -> satisfiable by phpdocumentor/reflection-docblock[2.0.4, 2.0.5].
>     - Can only install one of: phpdocumentor/reflection-docblock[2.0.4, 4.1.1].
>     - Can only install one of: phpdocumentor/reflection-docblock[2.0.5, 4.1.1].
>     - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].

**Comment by Firesphere** [comment]
I created this issue before 4 was released on the documentor, but absolutely agree!

**Comment by Firesphere** [comment]
Updated the title :)

You should not have any issues using 2.0, unless you have a reason to use 3+

**Comment by ivoba** [comment]
I just started with SS4. But as i see 2.0 should also work with SS4, right?

**Comment by Firesphere** [comment]
Should work, yes. But that doesn't mean we should upgrade our dependencies. It's just low on the priority list ;)

**Comment by ivoba** [comment]
Unfortunatly 2.0 has the same incompatibility with phpdocumentor/reflection-docblock.
Maybe raise the priority ;)

**Comment by brupy** [comment]
3.0-beta1 is not compatible with ss4. Composer wont install with phpdocumentor/reflection-docblock on version 4. And with phpdocumentor/reflection-docblock on version 2.0.5 composer does install, but the annotator gives an exception on build.

```
[Emergency] Uncaught Error: Call to a member function moduleIsAllowed() on null
GET ...../dev/build

Line 128 in .....\ideannotator\src\DataObjectAnnotator.php
```

Does somebody know how to get the annotator work on ss4? Maybe the priority of this issue should be raised as ivoba suggested.

**Comment by robbieaverill** [comment]
Here's what I think is happening:

* phpunit/phpunit 5.7 requires phpspec/prophecy 1.7
* phpspec/prophecy 1.7 requires phpdocumenter/reflection-docblock (^2.0|^3.0.2|^4.0)
* ideannotator requires phpdocumenter/reflection-docblock ^2.0@dev

So I think if you've installed SS4 from a fresh install with the dev dependencies (phpunit) you'll get reflection-docblock ^4.0 by default, so then installing this module will fail. If you've been upgrading from previous versions of SS4 where phpunit was a lower version you might not have had the same problem.

It looks like because the constraint for prophecy is very loose, you could just manually install an older version of reflection-docblock:

```
composer require phpdocumenter/reflection-docblock ^2.0
```

Then you should be able to install ideannotator correctly. This would at least be a workaround for now.

**Comment by Firesphere** [comment]
I can't reproduce the issue the way described by @robbieaverill .
Although I'm looking at going to v4, I'm still not seeing the issue happening

**Comment by jelicanin** [comment]
Just stumbled upon this issue on my project.

@robbieaverill  solution works, package needs to be downgraded manually:
`composer require phpdocumentor/reflection-docblock ^2.0`

**Comment by madmatt** [comment]
Yep I found the same thing that Robbie mentioned, starting with a new dev SS 4.2 site, phpunit ends up installing the `^4` version of `phpdocumenter/reflection-docblock`. Explicitly adding `^2` to composer.json resolves this.

Only suggestion I have is to use `composer require --dev phpdocumentor/reflection-docblock ^2` so it only gets added to dev sites and not a standard `composer install`.

**Comment by madmatt** [comment]
lol, I just spent a bunch of time attempting to figure this out, only to stumble on this issue again, and realise that I had this issue earlier in the year already and figured it out then 😂 

As noted, the way to resolve the issue where composer can't install this module is to do the following:
```composer require --dev phpdocumentor/reflection-docblock ^2
composer require --dev silverleague/ideannotator```

**Comment by gordonbanderson** [comment]
Fixed the issue I was having :)
